apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/values/no_proxy
          value: ".cluster.local.,.cluster.local,.svc,10.0.0.0/8,192.168.0.0/16,127.0.0.1"
      target:
        kind: HelmRelease
        name: cert-manager
    - patch: |
        - op: replace
          path: /spec/values/alertmanager/enabled
          value: true
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-staging-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack-fluxcd
  namespace: flux-system
spec:
  type: slack
  channel: "#mqex-fluxcd"
  secretRef:
    name: slack-fluxcd-webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-fluxcd-webhook
  namespace: flux-system
stringData:
  address: "https://hooks.slack.com/services/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"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "cluster addons"
  eventMetadata:
    env: "staging"
    cluster: "staging"
    region: "pk-east-1"
  providerRef:
    name: slack-fluxcd
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
