---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/component: monitoring

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/prometheus-community/charts

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 12h
  url: https://grafana.github.io/helm-charts

---

apiVersion: v1
kind: Service
metadata:
  name: discord-url
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/component: monitoring
  ports:
    - name: discord
      protocol: TCP
      port: 9093
      targetPort: 9093

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-alertmanager
  template:
    metadata:
      labels:
        app: discord-alertmanager
    spec:
      containers:
        - name: discord-alertmanager
          image: quay.io/prometheus/alertmanager:v0.23.0
          args:
            - "--config.file=/etc/alertmanager/config/alertmanager.yml"
            - "--storage.path=/alertmanager"
            - "--web.external-url="
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager/config
            - name: storage-volume
              mountPath: /alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: storage-volume
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      receiver: 'discord'
      routes:
        - match:
            alertname: 'Watchdog'
          receiver: 'discord'
    receivers:
      - name: 'discord'
        webhook_configs:
          - url: 'https://discordapp.com/api/webhooks/1246044427005202432/X5TYJG3z5e5BgZqfe8OxLUMpBr-_s4mny9--LBjovES9CJhFFPXb0bEOS16cLHKYXu_y'
